name: 'Comment sonar'
description: 'Detect TODO/FIXME comments and create/update a GitHub Issue'
author: 'rn404'
branding:
  icon: 'list'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub Token for authentication.'
    required: false
    default: '${{ github.token }}'
  github_repository:
    description: 'Repository to operate on.'
    required: false
    default: '${{ github.repository }}'
  sonar_includes:
    description: 'Glob patterns to include.'
    required: false
    default: '**/*'
  sonar_excludes:
    description: 'Glob patterns to exclude.'
    required: false
    default: ''
  issue_title:
    description: 'Title of the GitHub Issue.'
    required: false
    default: ':pushpin: TODO/FIXME List'
  issue_label:
    description: 'Label to apply to the GitHub Issue.'
    required: false
    default: 'TODO'

runs:
  using: 'composite'
  steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: 2.2.6
    - run: deno task run
      shell: bash
