name: 'Todo Comment Scanner'
description: 'Scan TODO/FIXME comments and create/update a GitHub Issue'
author: 'rn404'
branding:
  icon: 'list'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub Token for authentication'
    required: false
    default: '${{ github.token }}'
  github_repository:
    description: 'GitHub Repository to scan'
    required: false
    default: '${{ github.repository }}'
  sonar_paths:
    description: 'Paths to scan for TODO/FIXME comments'
    required: false
    default: '**/*'
  sonar_ignores:
    description: 'Paths to ignore during the scan'
    required: false
    default: ''
  issue_title:
    description: 'Title of the GitHub Issue'
    required: false
    default: ':pushpin: TODO/FIXME Comments Found'
  issue_label:
    description: 'Labels to apply to the GitHub Issue'
    required: false
    default: 'TODO'

runs:
  using: 'composite'
  steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: 2.2.6
    - run: deno task run
      shell: bash
