name: 'Comment sonar'
description: 'Detect TODO/FIXME comments and create/update a GitHub Issue'
author: 'rn404'
branding:
  icon: 'list'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub Token for authentication.'
    required: false
    default: '${{ github.token }}'
  github_repository:
    description: 'Repository to operate on.'
    required: false
    default: '${{ github.repository }}'
  sonar_includes:
    description: 'Glob patterns to include.'
    required: false
    default: '**/*'
  sonar_excludes:
    description: 'Glob patterns to exclude.'
    required: false
    default: ''
  issue_title:
    description: 'Title of the GitHub Issue.'
    required: false
    default: ':pushpin: TODO/FIXME List'
  issue_label:
    description: 'Label to apply to the GitHub Issue.'
    required: false
    default: 'TODO'

runs:
  using: 'composite'
  steps:
    - uses: denoland/setup-deno@v2
      with:
        deno-version: 2.2.6
    - run: |
        cd ${{ github.action_path }}
        deno task run
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_SONAR_INCLUDES: ${{ inputs.sonar_includes }}
        INPUT_SONAR_EXCLUDES: ${{ inputs.sonar_excludes }}
        INPUT_ISSUE_TITLE: ${{ inputs.issue_title }}
        INPUT_ISSUE_LABEL: ${{ inputs.issue_label }}
