name: Todo Comment Sonar
description: Detect TODO/FIXME comments and create/update a GitHub Issue

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 1' # 毎週月曜9時に実行

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.2.6

      - name: Run Todo Comment Sonar
        run: deno task run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
