name: Todo Comment Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1' # 毎週月曜9時に実行

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.2.6

      - name: Run Todo Comment Scanner
        run: deno -c .config/deno.json --lock=.config/deno.lock run --allow-read --allow-env --allow-net src/main.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
